IF OBJECT_ID('PLAYER') IS NOT NULL
DROP TABLE PLAYER

IF OBJECT_ID('TURN') IS NOT NULL
DROP TABLE TURN
GO


CREATE TABLE PLAYER
(
    USERNAME NVARCHAR(20),
    PRIMARY KEY (USERNAME)
);

CREATE TABLE TURN
(
    USERNAME NVARCHAR(20),
    DATE_TIME DATETIME,
    PLAYER_SELECTION NVARCHAR(8),
    CHECK (PLAYER_SELECTION = "ROCK" OR PLAYER_SELECTION = "SCISSORS" OR PLAYER_SELECTION = "PAPER"),
    AI_SELECTION NVARCHAR(8),
    CHECK (AI_SELECTION = "ROCK" OR AI_SELECTION = "SCISSORS" OR AI_SELECTION = "PAPER"),
    PRIMARY KEY (USERNAME, DATE_TIME),
    FOREIGN KEY (USERNAME) REFERENCES PLAYER
);
GO