IF OBJECT_ID('PLAYER') IS NOT NULL
DROP TABLE PLAYER

IF OBJECT_ID('GAME') IS NOT NULL
DROP TABLE GAME

IF OBJECT_ID('TURN') IS NOT NULL
DROP TABLE TURN
GO


CREATE TABLE PLAYER
(
    USERNAME NVARCHAR(20),
    PRIMARY KEY (USERNAME)
);

CREATE TABLE GAME
(
    USERNAME NVARCHAR(20),
    DATETIME_STARTED DATETIME,
    RESULT CHAR,
    CHECK (RESULT = "W" OR RESULT = "L" OR RESULT = "D"),
    NUMTURNS INT,
    CHECK (NUMTURNS = 1 OR NUMTURNS = 3 OR NUMTURNS = 5),
    PRIMARY KEY (USERNAME, DATETIME_STARTED),
    FOREIGN KEY (USERNAME) REFERENCES PLAYER
);

CREATE TABLE TURN
(
    USERNAME NVARCHAR(20),
    DATETIME_STARTED DATETIME,
    TURNNUM INT,
    CHECK (TURNNUM < 6),
    PLAYER_SELECTION NVARCHAR(8),
    CHECK (PLAYER_SELECTION = "ROCK" OR PLAYER_SELECTION = "SCISSORS" OR PLAYER_SELECTION = "PAPER"),
    AI_SELECTION NVARCHAR(8),
    CHECK (AI_SELECTION = "ROCK" OR AI_SELECTION = "SCISSORS" OR AI_SELECTION = "PAPER"),
    PRIMARY KEY (USERNAME, DATETIME_STARTED, TURNNUM),
    FOREIGN KEY (USERNAME) REFERENCES PLAYER,
    FOREIGN KEY (DATETIME_STARTED) REFERENCES GAME
);
GO